name: Release

on:
  push:
   tags:
     - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract release notes from CHANGELOG.md
        id: extract_release_notes
        run: |
          TAG="${{ github.ref_name }}"
          awk "/## \[${TAG}\]/,/## \[/" CHANGELOG.md > release_notes.md

      - name: Create GitHub Release  
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: release_notes.md

        
      
      